% Returns Spinach regression test metadata. Syntax:
%
%                    manifest=test_manifest()
%
% Outputs:
%
%     manifest  - structure array with test identifiers and functions
%
% ilya.kuprov@weizmann.ac.il

function manifest=test_manifest()

% Hand-written physically motivated tests
manifest=[...
    test_entry('kernel/pauli_spin_half_algebra','Spin-half angular momentum algebra','test_pauli_spin_half_algebra'),...
    test_entry('kernel/pauli_spin_one_algebra','Spin-one angular momentum algebra','test_pauli_spin_one_algebra'),...
    test_entry('kernel/commutator_utility','Matrix commutator utility','test_commutator_utility'),...
    test_entry('kernel/euler_rotation_matrix','Euler active rotation matrix','test_euler_rotation_matrix'),...
    test_entry('kernel/ppm_hz_roundtrip','Chemical-shift frequency conversion','test_ppm_hz_roundtrip'),...
    test_entry('kernel/remtrace_tensor','Traceless rank-two tensor construction','test_remtrace_tensor'),...
    test_entry('kernel/wave_basis_orthonormality','Waveform basis orthonormality','test_wave_basis_orthonormality'),...
    test_entry('kernel/rf_cartesian_polar','RF Cartesian/polar conversion','test_rf_cartesian_polar'),...
    test_entry('kernel/hilbert_operator','Hilbert-space operator generation','test_hilbert_operator'),...
    test_entry('kernel/hilbert_state','Hilbert-space state generation','test_hilbert_state'),...
    test_entry('kernel/zeeman_hamiltonian','Zeeman Hamiltonian sign and units','test_zeeman_hamiltonian'),...
    test_entry('kernel/scalar_coupling_hamiltonian','Scalar coupling Hamiltonian','test_scalar_coupling_hamiltonian'),...
    test_entry('kernel/liouville_commutator','Liouville commutation superoperator','test_liouville_commutator'),...
    test_entry('kernel/step_zero_time','Zero-duration propagation identity','test_step_zero_time'),...
    test_entry('kernel/step_matches_expm','Hilbert propagation against expm','test_step_matches_expm'),...
    test_entry('kernel/pi_pulse_rotation','Hard pi pulse rotation','test_pi_pulse_rotation'),...
    test_entry('kernel/shaped_pulse_rotation','Piecewise Cartesian pulse rotation','test_shaped_pulse_rotation'),...
    test_entry('kernel/relaxation_t2_rate','Phenomenological T2 decay rate','test_relaxation_t2_rate'),...
    test_entry('kernel/chemical_exchange_conservation','Chemical exchange conservation','test_chemical_exchange_conservation'),...
    test_entry('kernel/liquid_single_spin_fid','Single-spin liquid-state FID','test_liquid_single_spin_fid'),...
    test_entry('kernel/apodisation_exp_window','Exponential FID apodisation','test_apodisation_exp_window')];

end


function entry=test_entry(id,name,function_name)

% Build one manifest entry
entry.id=id;
entry.name=name;
entry.function=function_name;

end
