% Returns Spinach regression test metadata. Syntax:
%
%                    manifest=test_manifest()
%
% Outputs:
%
%     manifest  - structure array with test identifiers and functions
%
% ilya.kuprov@weizmann.ac.il

function manifest=test_manifest()

% Hand-written physically motivated tests
manifest=[...
    test_entry('kernel/pauli_spin_half_algebra','Spin-half angular momentum algebra','test_pauli_spin_half_algebra'),...
    test_entry('kernel/pauli_spin_one_algebra','Spin-one angular momentum algebra','test_pauli_spin_one_algebra'),...
    test_entry('kernel/commutator_utility','Matrix commutator utility','test_commutator_utility'),...
    test_entry('kernel/dynamic_filter_frontends','Dynamic state-filter front ends','test_dynamic_filter_frontends'),...
    test_entry('kernel/dynamic_frame_frontends','Dynamic frame and averaging front ends','test_dynamic_frame_frontends'),...
    test_entry('kernel/dynamic_propagation_frontends','Dynamic propagation front ends','test_dynamic_propagation_frontends'),...
    test_entry('kernel/dynamic_equilibrium_frontends','Dynamic equilibrium front ends','test_dynamic_equilibrium_frontends'),...
    test_entry('kernel/dynamic_trajectory_frontends','Dynamic trajectory analysis front ends','test_dynamic_trajectory_frontends'),...
    test_entry('kernel/euler_rotation_matrix','Euler active rotation matrix','test_euler_rotation_matrix'),...
    test_entry('kernel/transform_roundtrip_suite','Coordinate and tensor transform functions','test_transform_roundtrip_suite'),...
    test_entry('kernel/transform_rotation_suite','Rotation transform helpers','test_transform_rotation_suite'),...
    test_entry('kernel/transform_tensor_suite','Tensor transform helpers','test_transform_tensor_suite'),...
    test_entry('kernel/transform_units_coordinates_suite','Unit and coordinate transforms','test_transform_units_coordinates_suite'),...
    test_entry('kernel/indexing_roundtrip_suite','Indexing conversion functions','test_indexing_roundtrip_suite'),...
    test_entry('kernel/indexing_inverse_suite','Indexing inverse helpers','test_indexing_inverse_suite'),...
    test_entry('kernel/grid_geometry_suite','Grid and spherical geometry helpers','test_grid_geometry_suite'),...
    test_entry('kernel/ppm_hz_roundtrip','Chemical-shift frequency conversion','test_ppm_hz_roundtrip'),...
    test_entry('kernel/unit_conversion_suite','Unit-conversion functions','test_unit_conversion_suite'),...
    test_entry('kernel/remtrace_tensor','Traceless rank-two tensor construction','test_remtrace_tensor'),...
    test_entry('kernel/wave_basis_orthonormality','Waveform basis orthonormality','test_wave_basis_orthonormality'),...
    test_entry('kernel/rf_cartesian_polar','RF Cartesian/polar conversion','test_rf_cartesian_polar'),...
    test_entry('kernel/hilbert_operator','Hilbert-space operator generation','test_hilbert_operator'),...
    test_entry('kernel/hilbert_state','Hilbert-space state generation','test_hilbert_state'),...
    test_entry('kernel/state_constructor_suite','State-constructor functions','test_state_constructor_suite'),...
    test_entry('kernel/states_composite_suite','Composite state generators','test_states_composite_suite'),...
    test_entry('kernel/dynamic_state_equilibrium_suite','Thermal equilibrium constructors','test_dynamic_state_equilibrium_suite'),...
    test_entry('kernel/dynamic_state_projection_suite','Dynamic state projection helpers','test_dynamic_state_projection_suite'),...
    test_entry('kernel/dynamic_relaxation_models_suite','Dynamic relaxation model helpers','test_dynamic_relaxation_models_suite'),...
    test_entry('kernel/dynamic_rlx_split_suite','Relaxation component splitting','test_dynamic_rlx_split_suite'),...
    test_entry('kernel/operator_conversion_suite','Hilbert/Liouville conversion helpers','test_operator_conversion_suite'),...
    test_entry('kernel/operator_basis_suite','Operator-basis construction functions','test_operator_basis_suite'),...
    test_entry('kernel/operator_elementary_suite','Elementary operator generators','test_operator_elementary_suite'),...
    test_entry('kernel/operator_expansion_suite','Operator expansion and conversion helpers','test_operator_expansion_suite'),...
    test_entry('optimcon/grape_one_spin','One-spin optimal-control setup and GRAPE gradient','test_optimcon_grape_one_spin'),...
    test_entry('optimcon/support_paths','Optimal-control support helper paths','test_optimcon_support_paths'),...
    test_entry('kernel/matrix_utility_suite','Matrix utility functions','test_matrix_utility_suite'),...
    test_entry('kernel/lowlevel_utilities_suite','Low-level utility functions','test_lowlevel_utilities_suite'),...
    test_entry('kernel/finite_difference_suite','Finite-difference and spectral differentiation functions','test_finite_difference_suite'),...
    test_entry('kernel/sparse_tensor_utility_suite','Sparse, tensor, and numerical utility functions','test_sparse_tensor_utility_suite'),...
    test_entry('kernel/sparse_tensor_graph_suite','Sparse, tensor, and graph helper functions','test_sparse_tensor_graph_suite'),...
    test_entry('kernel/overload_arithmetic_suite','Cheap overload arithmetic','test_overload_arithmetic_suite'),...
    test_entry('kernel/cache_temp_scratch','Temporary scratch cache management','test_cache_temp_scratch'),...
    test_entry('kernel/wigner_angular_suite','Angular-momentum coefficient functions','test_wigner_angular_suite'),...
    test_entry('kernel/zeeman_hamiltonian','Zeeman Hamiltonian sign and units','test_zeeman_hamiltonian'),...
    test_entry('kernel/scalar_coupling_hamiltonian','Scalar coupling Hamiltonian','test_scalar_coupling_hamiltonian'),...
    test_entry('kernel/liouville_commutator','Liouville commutation superoperator','test_liouville_commutator'),...
    test_entry('kernel/step_zero_time','Zero-duration propagation identity','test_step_zero_time'),...
    test_entry('kernel/step_matches_expm','Hilbert propagation against expm','test_step_matches_expm'),...
    test_entry('kernel/pi_pulse_rotation','Hard pi pulse rotation','test_pi_pulse_rotation'),...
    test_entry('kernel/shaped_pulse_rotation','Piecewise Cartesian pulse rotation','test_shaped_pulse_rotation'),...
    test_entry('kernel/relaxation_t2_rate','Phenomenological T2 decay rate','test_relaxation_t2_rate'),...
    test_entry('kernel/chemical_exchange_conservation','Chemical exchange conservation','test_chemical_exchange_conservation'),...
    test_entry('kernel/kinetics_generator_suite','Kinetics and flow generator functions','test_kinetics_generator_suite'),...
    test_entry('kernel/kinetics_invariants_suite','Chemical kinetics invariants','test_kinetics_invariants_suite'),...
    test_entry('kernel/pulses_waveform_suite','Pulse waveform generators','test_pulses_waveform_suite'),...
    test_entry('kernel/pulses_propagation_suite','Pulse coordinate and propagation helpers','test_pulses_propagation_suite'),...
    test_entry('kernel/dynamic_shaped_pulses_deep','Dynamic shaped pulse propagation paths','test_dynamic_shaped_pulses_deep'),...
    test_entry('kernel/dynamic_pulse_utilities_deep','Dynamic pulse utility paths','test_dynamic_pulse_utilities_deep'),...
    test_entry('kernel/dynamic_iserstep_highorder','Nonlinear high-order iserstep branches','test_dynamic_iserstep_highorder'),...
    test_entry('kernel/ctx_liquid_acquire','Liquid context acquire path','test_ctx_liquid_acquire'),...
    test_entry('kernel/ctx_powder_crystal','Powder and crystal single orientation','test_ctx_powder_crystal'),...
    test_entry('kernel/ctx_powder_average','Powder weighted sum path','test_ctx_powder_average'),...
    test_entry('kernel/ctx_singlerot_acquire','Single-rotor acquire path','test_ctx_singlerot_acquire'),...
    test_entry('kernel/ctx_floquet_acquire','Floquet acquire path','test_ctx_floquet_acquire'),...
    test_entry('kernel/ctx_gridfree_acquire','Grid-free acquire path','test_ctx_gridfree_acquire'),...
    test_entry('kernel/ctx_doublerot_acquire','Double-rotor acquire path','test_ctx_doublerot_acquire'),...
    test_entry('kernel/orientation_average_suite','Orientation and average helpers','test_orientation_average_suite'),...
    test_entry('kernel/plotting_helpers_offscreen','Offscreen plotting helpers','test_plotting_helpers_offscreen'),...
    test_entry('examples/dynamic_examples_smoke','Dynamic plotting example smoke paths','test_dynamic_examples_smoke'),...
    test_entry('kernel/liquid_single_spin_fid','Single-spin liquid-state FID','test_liquid_single_spin_fid'),...
    test_entry('kernel/apodisation_exp_window','Exponential FID apodisation','test_apodisation_exp_window')];

end


function entry=test_entry(id,name,function_name)

% Build one manifest entry
entry.id=id;
entry.name=name;
entry.function=function_name;

end
