% Digital processing for a recording of the proton optimal 
% control pulse, done on a 1 GHz oscilloscope using the 13C
% coil of the same probe: the pulse is heterodyned down to
% the rotating frame and compared with the ideal version.
%
% a.acharya@soton.ac.uk
% ilya.kuprov@weizmann.ac.il

function pulse_heterodyne()

% Import pulse as generated by instrument 
load('scope_readout.mat','time_grid','expt_data');

% Convert to double precision
time_grid=double(time_grid);
expt_data=double(expt_data);

% Plot the raw scope readout
kfigure(); scale_figure([2.0 1.5]);
subplot(2,2,1); plot(time_grid,expt_data); 
xlim([0 0.05]); ylim padded; kgrid; 
ktitle('wall clock'); kxlabel('time, s');

% Carrier frequency and timing
carrier_freq=500.1029395e6;
dt=time_grid(2)-time_grid(1);
                                  
% Apply heterodyne transformation wrt carrier frequency
[real_bruk,imag_bruk]=heterodyne(dt,expt_data,carrier_freq);

% Resample and convert to complex
real_bruk=resample(real_bruk,1,10000);
imag_bruk=resample(imag_bruk,1,10000);
time_grid=linspace(time_grid(1),...
                   time_grid(end),...
                   numel(real_bruk))';
cplx_bruk=real_bruk+1i*imag_bruk;
ampl_bruk=abs(cplx_bruk);

% Empirical initial phase offset
cplx_bruk=exp(1i*2.338)*cplx_bruk;

% Load the pulse produced by optimal control
load('ideal_pulse.mat','pulse'); pulse(:,end+1)=0;
time_theo=linspace(0,0.1,size(pulse,2));
cplx_theo=pulse(1,:)+1i*pulse(2,:);
ampl_theo=abs(cplx_theo);

% Match the experimental amplitude to theory
cplx_bruk=cplx_bruk*(max(ampl_theo)/max(ampl_bruk));
ampl_bruk=ampl_bruk*(max(ampl_theo)/max(ampl_bruk));

% Plot the comparison of amplitudes
subplot(2,2,2); stairs(time_grid,ampl_bruk); 
hold on; stairs(time_theo,ampl_theo');
xlim([0 0.05]); ylim padded; kgrid; 
ktitle('amplitude'); kxlabel('time, s');
klegend({'antenna','input'},'Location','northwest');

% Plot real part of both signals
subplot(2,2,3); stairs(time_grid,real(cplx_bruk)); 
hold on; stairs(time_theo,real(cplx_theo));
xlim([0 0.05]); ylim padded; kgrid; 
ktitle('in-phase component'); kxlabel('time, s');
klegend({'antenna','input'},'Location','southwest');

% Plot imaginary part of both signals
subplot(2,2,4); stairs(time_grid,imag(cplx_bruk));
hold on; stairs(time_theo,imag(cplx_theo));
xlim([0 0.05]); ylim padded; kgrid; 
ktitle('out-of-phase component'); kxlabel('time, s');
klegend({'antenna','input'},'Location','southwest');

end 

