% Reduced heteronuclear control demonstration inspired by the low-power
% offset-tolerant 14N decoupling papers of Nehra, Agarwal, and Nishiyama.
% The model uses an observed 1H spin coupled to a controlled 14N spin:
%
%   - controls act on 14N only,
%   - the optimisation target is preservation of 1H magnetisation,
%   - 14N offset and B1 distributions represent the practical decoupling
%     problem,
%   - the Bloch-Siegert term is generated by, and applied to, the driven
%     14N channel.
%
% This is deliberately a reduced effective model rather than a full MAS
% quadrupolar simulation. In particular, the broad 14N quadrupolar/MAS
% response is compressed into an effective 14N offset ensemble, and the
% NH interaction is represented by a simple two-spin coupling. The point
% of the example is to demonstrate the control logic of the Yusuke use
% case inside the current Bloch-Siegert-aware GRAPE framework.
%
% aditya.dev@weizmann.ac.il

function yusuke_1h_14n_optimal_vs_cw_demo()

rng(1);

% Magnetic field corresponding to 800 MHz 1H
sys.magnet=18.8;

% Minimal heteronuclear model: one observed 1H and one controlled 14N
sys.isotopes={'1H','14N'};
inter.zeeman.scalar={0,0};
inter.coupling.scalar=cell(2);

% Effective NH interaction to be refocused by 14N irradiation. This is a
% reduced-model surrogate for the residual proton-nitrogen interaction in
% the decoupling problem, not a literal full solid-state Hamiltonian.
inter.coupling.scalar{1,2}=1500;

% Basis set
bas.formalism='sphten-liouv';
bas.approximation='none';

% Spinach housekeeping
spin_system=create(sys,inter);
spin_system=basis(spin_system,bas);

% Observed 1H states used to define the transverse-preservation target.
% Only transverse magnetisation is used because that is the part directly
% relevant to proton line preservation during decoupling.
Hx=state(spin_system,'Lx','1H'); Hx=Hx/norm(full(Hx),2);
Hy=state(spin_system,'Ly','1H'); Hy=Hy/norm(full(Hy),2);

% 14N control and shift operators
LxN=operator(spin_system,'Lx','14N');
LyN=operator(spin_system,'Ly','14N');
LzN=operator(spin_system,'Lz','14N');

% Drift Hamiltonian
H=hamiltonian(assume(spin_system,'nmr'));

% Paper-inspired practical regime:
%   - 800 MHz 1H field
%   - low-power 14N irradiation around 15-23 kHz
%   - 10 us pulse elements
%   - a millisecond-scale decoupling block rather than a single very short
%     cycle, because the proton dephasing and Bloch-Siegert accumulation
%     become visible over acquisition-time decoupling windows
% The offset windows below are intentionally narrower than a full
% quadrupolar powder/MAS treatment because this is an effective model.
rf_nominal_hz=20e3;
nsteps=120;
pulse_dt=10e-6*ones(1,nsteps);
train_offsets_hz=linspace(-12e3,12e3,7);
train_b1_scales=[0.95 1.00 1.05];
eval_offsets_hz=linspace(-20e3,20e3,61);
eval_b1_scales=linspace(0.90,1.10,9);

% Define the phase-only optimisation problem on 14N with a 1H target
control.isotopes={'14N'}; 
control.channels=[1; 1];
control.drifts={{H}};
control.operators={LxN,LyN};
control.rho_init={Hx Hy};
control.rho_targ={Hx Hy};
control.off_ops={LzN};
control.offsets={train_offsets_hz};
control.pwr_levels=2*pi*rf_nominal_hz*train_b1_scales;
control.amplitudes=ones(1,nsteps);
control.pulse_dt=pulse_dt;
control.fidelity='square';
control.method='lbfgs';
control.max_iter=40;
control.plotting={};

% Bloch-Siegert correction on the driven 14N channel
control.bsiegert=true();

% Spinach housekeeping
spin_system_bs=optimcon(spin_system,control);

% Optimise a low-power phase-modulated 14N cycle. The seed is an XY-type
% phase cycle rather than a random guess because the heteronuclear
% preservation problem is structured; random initial phases can give
% exactly zero overlap for some ensemble members and make GRAPE abort.
guess=reshape((pi/2)*mod(0:nsteps-1,4),1,[]);
phi_opt=fmaxnewton(spin_system_bs,@grape_phase,guess);

% Constant-phase baseline with the same duration and RF power
phi_cw=zeros(1,nsteps);

% Evaluate both waveforms on dense 14N offset and B1 grids
[profile_opt,mean_offset_opt]=offset_profile(spin_system_bs,H,{LxN,LyN},...
    control.pulse_dt,Hx,Hy,LzN,phi_opt,rf_nominal_hz,eval_offsets_hz,...
    eval_b1_scales);

[profile_cw,mean_offset_cw]=offset_profile(spin_system_bs,H,{LxN,LyN},...
    control.pulse_dt,Hx,Hy,LzN,phi_cw,rf_nominal_hz,eval_offsets_hz,...
    eval_b1_scales);

[~,mean_b1_opt]=b1_profile(spin_system_bs,H,{LxN,LyN},...
    control.pulse_dt,Hx,Hy,LzN,phi_opt,rf_nominal_hz,eval_offsets_hz,...
    eval_b1_scales);

[~,mean_b1_cw]=b1_profile(spin_system_bs,H,{LxN,LyN},...
    control.pulse_dt,Hx,Hy,LzN,phi_cw,rf_nominal_hz,eval_offsets_hz,...
    eval_b1_scales);

% Training-set figures of merit
train_opt=ensemble_score(spin_system_bs,H,{LxN,LyN},control.pulse_dt,...
    Hx,Hy,LzN,phi_opt,rf_nominal_hz,train_offsets_hz,train_b1_scales);

train_cw=ensemble_score(spin_system_bs,H,{LxN,LyN},control.pulse_dt,...
    Hx,Hy,LzN,phi_cw,rf_nominal_hz,train_offsets_hz,train_b1_scales);

% Plot the result
figure;
time_axis_us=cumsum(control.pulse_dt)*1e6;

subplot(3,1,1);
plot(time_axis_us,unwrap(phi_opt),'LineWidth',1.2); hold on;
plot(time_axis_us,phi_cw,'LineWidth',1.2);
grid on;
xlabel('Time / \mus');
ylabel('14N phase / rad');
title('Optimised 14N phase cycle versus constant-phase CW-like baseline');
legend({'Optimised','Constant-phase'},'Location','Best');

subplot(3,1,2);
plot(eval_offsets_hz/1e3,mean_offset_opt,'LineWidth',1.5); hold on;
plot(eval_offsets_hz/1e3,mean_offset_cw,'LineWidth',1.5);
grid on;
xlabel('14N offset / kHz');
ylabel('Mean 1H preservation fidelity');
title('Average over B_1 distribution');
legend({'Optimised','Constant-phase'},'Location','SouthWest');

subplot(3,1,3);
plot(eval_b1_scales,mean_b1_opt,'LineWidth',1.5); hold on;
plot(eval_b1_scales,mean_b1_cw,'LineWidth',1.5);
grid on;
xlabel('14N B_1 scaling factor');
ylabel('Mean 1H preservation fidelity');
title('Average over 14N offset distribution');
legend({'Optimised','Constant-phase'},'Location','SouthWest');

% Secondary robustness figures
figure;

subplot(2,1,1);
imagesc(eval_offsets_hz/1e3,eval_b1_scales,profile_opt);
axis xy;
colorbar;
xlabel('14N offset / kHz');
ylabel('14N B_1 scaling factor');
title('Optimised pulse: 1H preservation map');

subplot(2,1,2);
imagesc(eval_offsets_hz/1e3,eval_b1_scales,profile_cw);
axis xy;
colorbar;
xlabel('14N offset / kHz');
ylabel('14N B_1 scaling factor');
title('Constant-phase baseline: 1H preservation map');

% Console summary
fprintf('\n');
fprintf('Yusuke 1H/14N reduced-model control demo\n');
fprintf('  Training ensemble mean fidelity, optimised:      %.4f\n',mean(train_opt(:)));
fprintf('  Training ensemble mean fidelity, constant phase: %.4f\n',mean(train_cw(:)));
fprintf('  Training ensemble worst-case fidelity, optimised:      %.4f\n',min(train_opt(:)));
fprintf('  Training ensemble worst-case fidelity, constant phase: %.4f\n',min(train_cw(:)));
fprintf('\n');
fprintf(['Interpretation: the optimised pulse is a low-power 14N waveform ' ...
         'trained to preserve the observed 1H signal across 14N offsets ' ...
         'and B1 variation, while the constant-phase pulse is the CW-like ' ...
         'baseline.\n']);
fprintf(['Model note: this is a reduced heteronuclear demonstration of the ' ...
         'paper mechanism, not a full quadrupolar MAS simulation.\n']);

end

function [score_map,mean_profile]=offset_profile(spin_system,H,controls,...
    pulse_dt,Hx,Hy,LzN,phi_profile,rf_nominal_hz,offsets_hz,b1_scales)

% Fidelity map across 14N offsets and B1 scales
score_map=zeros(numel(b1_scales),numel(offsets_hz));
for n=1:numel(offsets_hz)
    for k=1:numel(b1_scales)
        score_map(k,n)=single_score(spin_system,H,controls,pulse_dt,...
            Hx,Hy,LzN,phi_profile,rf_nominal_hz,offsets_hz(n),b1_scales(k));
    end
end
mean_profile=mean(score_map,1);

end

function [score_map,mean_profile]=b1_profile(spin_system,H,controls,...
    pulse_dt,Hx,Hy,LzN,phi_profile,rf_nominal_hz,offsets_hz,b1_scales)

% Fidelity map across 14N offsets and B1 scales
score_map=zeros(numel(b1_scales),numel(offsets_hz));
for n=1:numel(offsets_hz)
    for k=1:numel(b1_scales)
        score_map(k,n)=single_score(spin_system,H,controls,pulse_dt,...
            Hx,Hy,LzN,phi_profile,rf_nominal_hz,offsets_hz(n),b1_scales(k));
    end
end
mean_profile=mean(score_map,2);

end

function score=ensemble_score(spin_system,H,controls,pulse_dt,Hx,Hy,...
    LzN,phi_profile,rf_nominal_hz,offsets_hz,b1_scales)

% Training-ensemble fidelity matrix
score=zeros(numel(b1_scales),numel(offsets_hz));
for n=1:numel(offsets_hz)
    for k=1:numel(b1_scales)
        score(k,n)=single_score(spin_system,H,controls,pulse_dt,...
            Hx,Hy,LzN,phi_profile,rf_nominal_hz,offsets_hz(n),b1_scales(k));
    end
end

end

function score=single_score(spin_system,H,controls,pulse_dt,Hx,Hy,...
    LzN,phi_profile,rf_nominal_hz,offset_hz,b1_scale)

% Build the physical 14N waveform
amp_profile=2*pi*rf_nominal_hz*b1_scale*ones(size(phi_profile));
[CNx,CNy]=polar2cartesian(amp_profile,phi_profile);


% Apply the Bloch-Siegert-aware 14N pulse in a 14N-offset ensemble member
[controls_aug,pulse_aug]=bloch_siegert(spin_system,controls,...
                                             {CNx,CNy});
rho=shaped_pulse_xy(spin_system,H+2*pi*offset_hz*LzN,controls_aug,...
                    pulse_aug,pulse_dt,[Hx,Hy],'expv-pwc');

% Average preservation fidelity across the observed 1H transverse states
score=real(trace([Hx,Hy]'*rho))/2;

end


