% Orbits the camera around a 3D plot and writes a correctly 
% looping 359-frame movie. Syntax:
%
%                   write_movie(file_name)
%
% This function is intended for generating presentation qua-
% lity 3D movies from graphics generated by cst_display(),
% hfc_display(), and volplot().
%
% ilya.kuprov@weizmann.ac.il
%
% <https://spindynamics.org/wiki/index.php?title=write_movie.m>

function write_movie(file_name)

% Check consistency
grumble(file_name);

% Overrride stretch-to-fill
axis vis3d;

% Open the video writer object
writerObj=VideoWriter(file_name,'MPEG-4');
writerObj.Quality=100; open(writerObj);

% Orbit the camera
for n=1:359
    
    % Grab the frame
    writeVideo(writerObj,getframe(gcf));
    pause(0.05); camorbit(1,0);
    
end

% Close the writer object
close(writerObj);

end

% Consistency enforcement
function grumble(file_name)
if ~ischar(file_name)
    error('file_name must be a character string.');
end
end

% Love is [...] friendship inspired by beauty.
%
% Marcus Tullius Cicero

