% Tests spin-half angular momentum matrices. Syntax:
%
%                    result=test_pauli_spin_half_algebra()
%
% Outputs:
%
%     result  - regression test result with explanatory messages
%
% The test checks that Pauli matrices generated by Spinach obey the
% spin-half angular momentum algebra, the ladder-operator convention, and
% the S^2=s(s+1) identity for s=1/2.
%
% ilya.kuprov@weizmann.ac.il

function result=test_pauli_spin_half_algebra()

% Announce the test target
fprintf('TESTING: Spin-half angular momentum algebra\n');

% State the physical target of the test
result=new_test_result('kernel/pauli_spin_half_algebra',...
                       'Spin-half angular momentum algebra',...
                       'Spin-half operators must realise the su(2) algebra and S^2=3/4.');

% Generate Spinach spin-half operators
S=pauli(2);

% Write the textbook matrices explicitly
Sx=[0 1;1 0]/2;
Sy=[0 -1i;1i 0]/2;
Sz=[1 0;0 -1]/2;
Sp=[0 1;0 0];
Sm=[0 0;1 0];

% Check the operator matrices against the textbook representation
result=test_close(result,'Sx textbook matrix',S.x,Sx,1e-15,1e-15,...
                  'spin-half Sx is half of the first Pauli matrix');
result=test_close(result,'Sy textbook matrix',S.y,Sy,1e-15,1e-15,...
                  'spin-half Sy is half of the second Pauli matrix');
result=test_close(result,'Sz textbook matrix',S.z,Sz,1e-15,1e-15,...
                  'spin-half Sz has projections +1/2 and -1/2');
result=test_close(result,'raising operator',S.p,Sp,1e-15,1e-15,...
                  'the raising operator converts beta into alpha');
result=test_close(result,'lowering operator',S.m,Sm,1e-15,1e-15,...
                  'the lowering operator converts alpha into beta');

% Check the angular momentum commutation relations
result=test_close(result,'[Sx,Sy]=iSz',comm(S.x,S.y),1i*S.z,1e-15,1e-15,...
                  'angular momentum generators must close under su(2)');
result=test_close(result,'[Sz,S+]=S+',comm(S.z,S.p),S.p,1e-15,1e-15,...
                  'S+ raises the magnetic quantum number by one');
result=test_close(result,'[Sz,S-]=-S-',comm(S.z,S.m),-S.m,1e-15,1e-15,...
                  'S- lowers the magnetic quantum number by one');

% Check the Casimir operator
S2=S.x*S.x+S.y*S.y+S.z*S.z;
result=test_close(result,'S^2=s(s+1)',S2,0.75*S.u,1e-15,1e-15,...
                  'for s=1/2 the Casimir eigenvalue is 3/4');

end

