% Tests adaptive propagator power evaluation. Syntax:
%
%                    result=test_multiprop_adaptive()
%
% Outputs:
%
%     result  - regression test result with explanatory messages
%
% The test checks binary adaptive squaring in multiprop() against explicit
% matrix-power references and verifies clean-up after propagator squaring.
%
% ilya.kuprov@weizmann.ac.il

function result=test_multiprop_adaptive()

% Announce the test target
fprintf('TESTING: Adaptive propagator power evaluation\n');

% State the propagation target of the test
result=new_test_result('kernel/multiprop_adaptive',...
                       'Adaptive propagator power evaluation',...
                       'multiprop() must compute propagator powers by binary adaptive squaring.');

% Build the minimum Spinach system fields required by clean_up()
spin_system.sys.enable={};
spin_system.sys.disable={};
spin_system.tols.prop_chop=0;
spin_system.tols.dense_matrix=0.15;
spin_system.tols.small_matrix=200;

% Define a non-normal sparse propagator
P=sparse([0.90 0.10 0.00;0.00 0.80 0.20;0.05 0.00 0.70]);
N=uint64(13);

% Compare adaptive squaring with an explicit matrix power
P_obs=multiprop(spin_system,P,N);
P_ref=P^double(N);
result=test_close(result,'sparse propagator power',P_obs,P_ref,1e-14,1e-14,...
                  'sparse propagator powers match explicit matrix powers');

% Define a diagonal sparse propagator
P=spdiags([0.95;0.80;0.65],0,3,3);
N=uint64(11);

% Compare sparse diagonal propagation with a matrix-power reference
P_obs=multiprop(spin_system,P,N);
P_ref=P^double(N);
result=test_close(result,'sparse diagonal power',P_obs,P_ref,1e-14,1e-14,...
                  'sparse diagonal propagators follow the generic squaring path');

% Define a Hilbert-space unitary propagator
S=pauli(2);
H=2*pi*(0.30*S.x+0.70*S.z);
P=expm(-1i*H*0.125);
N=15;

% Compare dense unitary propagation with an explicit matrix power
P_obs=multiprop(spin_system,P,N);
P_ref=P^N;
result=test_close(result,'dense unitary power',P_obs,P_ref,1e-13,1e-13,...
                  'dense unitary propagators match explicit matrix powers');

% Define a sparse non-unitary propagator
P=sparse([0.90 0.10 0.00;0.00 0.80 0.20;0.05 0.00 0.70]);
N=uint64(6);

% Compare sparse non-unitary propagation with an explicit matrix power
P_obs=multiprop(spin_system,P,N);
P_ref=P^double(N);
result=test_close(result,'sparse non-unitary power',P_obs,P_ref,1e-14,1e-14,...
                  'sparse non-unitary propagators follow direct binary-power accumulation');

% Define a diagonal complex propagator
P=spdiags(exp(1i*[0.10;0.20;0.30]),0,3,3);
N=uint64(7);

% Compare sparse diagonal complex propagation with an explicit matrix power
P_obs=multiprop(spin_system,P,N);
P_ref=P^double(N);
result=test_close(result,'sparse diagonal complex power',P_obs,P_ref,1e-13,1e-13,...
                  'complex sparse diagonal propagators follow the generic power path');

% Check the zero-power shortcut
P_obs=multiprop(spin_system,P,0);
P_ref=speye(size(P,1));
result=test_close(result,'zero power identity',P_obs,P_ref,1e-15,1e-15,...
                  'zero propagator power returns the identity matrix');

% Check the first-power shortcut
P_obs=multiprop(spin_system,P,1);
result=test_close(result,'first power shortcut',P_obs,P,1e-15,1e-15,...
                  'the first propagator power returns the original propagator');

% Check scalar branch consistency
P_obs=multiprop(spin_system,0.5,3);
result=test_close(result,'scalar propagator power',P_obs,0.125,1e-15,1e-15,...
                  'one-dimensional propagators follow the generic power path');

% Enable clean-up after propagator squaring
spin_system.tols.prop_chop=1e-6;

% Check cleanup after propagator squaring
P=speye(2)+sparse([0 1e-8;0 0]);
P_obs=multiprop(spin_system,P,4);
P_ref=speye(2);
result=test_close(result,'squaring cleanup',P_obs,P_ref,1e-15,1e-15,...
                  'small elements generated by propagator squaring are removed');

% Check non-square matrix rejection
caught=false;
try
    multiprop(spin_system,[1 0],3);
catch
    caught=true;
end

result=test_true(result,'non-square matrix rejection',caught,...
                 'non-square propagators are not valid Spinach propagators');

end
