% Compare function handle polyadic cores with explicit matrices.
% Syntax:
%
%                         result=test_fft_polyadic()
%
% Outputs:
%
%    result - regression checks for FFT actions, adjoints, and propagation
%
% ilya.kuprov@weizmann.ac.il

function result=test_fft_polyadic()

% Describe the independently materialised references
result=new_test_result('kernel/fft_polyadic','FFT polyadic cores',...
                       'Function handle cores must agree with explicit Fourier differentiation and exponentiation.');

% Exercise odd and even grids, including the zero Nyquist convention
for npoints=[1 2 3 8 9]
    [~,explicit]=fourdif(npoints,1);
    core=fft_core(npoints);
    block=reshape(sin(1:(3*npoints)),npoints,3)+...
          1i*reshape(cos(1:(3*npoints)),npoints,3);
    implicit=polyadic({{core,opium(2,1)}});
    reference=kron(explicit,eye(2));
    rhs=[block;block];
    result=test_close(result,['derivative ' num2str(npoints)],...
                      implicit*rhs,reference*rhs,1e-12,1e-12,...
                      'complex multiple right-hand sides match fourdif');
    result=test_close(result,['adjoint ' num2str(npoints)],...
                      implicit'*rhs,reference'*rhs,1e-12,1e-12,...
                      'the adjoint used in norm estimation is correct');
    result=test_close(result,['transpose ' num2str(npoints)],...
                      implicit.'*rhs,reference.'*rhs,1e-12,1e-12,...
                      'non-conjugating transpose has the correct sign');
    result=test_true(result,['size ' num2str(npoints)],...
                     isequal(size(implicit),[2*npoints 2*npoints]),...
                     'handle cores report their dimensions');
end

% A general complex rectangular handle tests dimensions and adjoints
matrix=[1+2i 2-1i 3;4 5i 6-2i];
core=struct('action',@(x)matrix*x,'adjoint',@(x)matrix'*x,'dims',size(matrix));
implicit=polyadic({{core,opium(2,1)}});
reference=kron(matrix,eye(2));
rhs=reshape(1:12,6,2);
result=test_close(result,'rectangular action',implicit*rhs,reference*rhs,...
                  1e-12,1e-12,'forward block dimensions are honoured');
result=test_close(result,'complex adjoint',(2i*implicit)'*reshape(1:8,4,2),...
                  (2i*reference)'*reshape(1:8,4,2),1e-12,1e-12,...
                  'scaling is absorbed by the matrix core and conjugated');
result=test_close(result,'complex transpose',implicit.'*reshape(1:8,4,2),...
                  reference.'*reshape(1:8,4,2),1e-12,1e-12,...
                  'transpose does not conjugate complex entries');
result=test_close(result,'double transpose',(implicit.').'*rhs,...
                  reference*rhs,1e-12,1e-12,...
                  'transposing twice restores the action');
result=test_close(result,'implicit composition',(implicit'*implicit)*rhs,...
                  reference'*reference*rhs,1e-12,1e-12,...
                  'composition buffers actions without multiplying cores');
result=test_close(result,'dense left action',ones(1,4)*implicit,...
                  ones(1,4)*reference,1e-12,1e-12,...
                  'dense left multiplication uses the adjoint route');
result=test_true(result,'handle structure',isa(simplify(polyadic({{core}})),'polyadic'),...
                 'a singleton handle core stays in the polyadic norm-estimation route');

% Arithmetic must preserve constructor metadata through core reordering
small=polyadic({{core}});
result=test_close(result,'numeric sum',(small+matrix)*ones(3,1),...
                  2*matrix*ones(3,1),1e-12,1e-12,'sum metadata stays aligned');
result=test_close(result,'implicit sum',(small+small)*ones(3,1),...
                  2*matrix*ones(3,1),1e-12,1e-12,'two implicit terms keep metadata');
result=test_close(result,'left Kronecker',kron(eye(2),small)*rhs,...
                  kron(eye(2),matrix)*rhs,1e-12,1e-12,'prepending a core keeps metadata');
result=test_close(result,'right Kronecker',kron(small,eye(2))*rhs,...
                  reference*rhs,1e-12,1e-12,'appending a core keeps metadata');
result=test_close(result,'zero scaling',(0*small)*ones(3,1),zeros(2,1),...
                  0,0,'zero terms and metadata are removed together');
result=test_true(result,'ordinary handle',isa(small.cores{1}{1},'function_handle'),...
                 'the stored core is an ordinary numerical action');
validate(small); allfinite(small); isreal(small); nnz(small);

% Affixes and nested flattening retain the actions and their dimensions
result=test_close(result,'scalar prefix',prefix(2i,small)*ones(3,1),...
                  2i*matrix*ones(3,1),1e-12,1e-12,'scalar prefix uses buffered arithmetic');
result=test_close(result,'scalar suffix',suffix(small,2i)*ones(3,1),...
                  2i*matrix*ones(3,1),1e-12,1e-12,'scalar suffix uses buffered arithmetic');
result=test_close(result,'nested flattening',simplify(polyadic({{eye(2),small}}))*rhs,...
                  kron(eye(2),matrix)*rhs,1e-12,1e-12,'flattened metadata tracks the cores');
result=test_close(result,'constructor roundtrip',polyadic(core_specs(small))*ones(3,1),...
                  matrix*ones(3,1),1e-12,1e-12,'construction descriptions preserve the action');

% Scalar affixes must preserve dimensions, even after zero scaling
result=test_true(result,'scalar prefix size',isequal(size(prefix(2i,small)),[2 3]),...
                 'a scalar prefix must preserve both matrix dimensions');
result=test_true(result,'scalar suffix size',isequal(size(suffix(small,2i)),[2 3]),...
                 'a scalar suffix must preserve both matrix dimensions');
result=test_true(result,'zero prefix size',isequal(size(simplify(prefix(0,small))),[2 3]),...
                 'a zero scalar prefix yields a zero matrix of the original size');
result=test_close(result,'prefix after scaling',prefix([1 2],prefix(2i,small))*ones(3,1),...
                  [1 2]*(2i*matrix)*ones(3,1),1e-12,1e-12,...
                  'a subsequent matrix prefix sees the correct row dimension');

% Scalar implicit operators must compose as actions, not as coefficients
scalar_core=struct('action',@(x)2i*x,'adjoint',@(x)-2i*x,'dims',[1 1]);
scalar_poly=polyadic({{scalar_core}});
result=test_close(result,'scalar core composition',(scalar_poly*scalar_poly)*ones(1,2),...
                  -4*ones(1,2),1e-12,1e-12,'scalar implicit operands are buffered');
column=[1;2i];
column_core=struct('action',@(x)column*x,'adjoint',@(x)column'*x,'dims',[2 1]);
result=test_close(result,'column scalar composition',...
                  (polyadic({{column_core}})*scalar_poly)*ones(1,2),...
                  2i*column*ones(1,2),1e-12,1e-12,...
                  'rectangular implicit operators compose with scalar implicit operators');

% Diagnostic output must use the represented dimensions, not handle sizes
diagram=evalc('polinfo(small,0,''implicit'');');
result=test_true(result,'implicit diagram',contains(diagram,'handle 1 [2x3]'),...
                 'polinfo labels the action with its stored dimensions');

% Explicit materialisation must not open function handle cores
result=check_rejection(result,'full rejection',@()full(implicit),...
                       'function handle cores cannot be materialised');
result=check_rejection(result,'inflate rejection',@()inflate(implicit),...
                       'function handle cores cannot be materialised');
result=test_close(result,'singleton scaling',(polyadic({{core}})*2i)'*ones(2,1),...
                  (matrix*2i)'*ones(2,1),1e-12,1e-12,...
                  'singleton implicit cores support scalar multiplication');

% Build a small Hermitian rotor generator with a noncommuting spin term
[~,explicit]=fourdif(9,1); core=fft_core(9);
spin_term=[1 0.3;0.3 -1];
reference=kron(diag(cos(2*pi*(0:8)/9)),spin_term)+...
          1i*kron(explicit,eye(2));
implicit=polyadic({{diag(cos(2*pi*(0:8)/9)),spin_term}})+...
         1i*polyadic({{core,opium(2,1)}});
spin_system.sys.enable={}; spin_system.sys.disable={};
spin_system.bas.formalism='zeeman-liouv'; spin_system.sys.output='hush';
spin_system.tols.prop_chop=1e-12;
spin_system.tols.dense_matrix=0.5; spin_system.tols.small_matrix=200;
rhs=reshape(sin(1:36),18,2)+1i*reshape(cos(1:36),18,2);
result=test_close(result,'Taylor propagation',...
                  step(spin_system,implicit,rhs,0.1),expm(-1i*reference*0.1)*rhs,...
                  1e-11,1e-11,'the existing step algorithm handles function handle cores');
result=test_close(result,'cleanup preserves action',...
                  clean_up(spin_system,implicit,eps)*rhs,reference*rhs,...
                  1e-12,1e-12,'cleanup does not touch opaque actions');

end

% FFT actions with the first derivative Nyquist convention of fourdif
function core=fft_core(npoints)
kern=fftdiff(1,npoints,2*pi/npoints).';
if mod(npoints,2)==0, kern(npoints/2+1)=0; end
core=struct('action',@(x)ifft(kern.*fft(x,[],1),[],1),...
            'adjoint',@(x)ifft(conj(kern).*fft(x,[],1),[],1),...
            'dims',[npoints npoints]);
end

% Check that explicit materialisation fails without opening an action
function result=check_rejection(result,label,action,expected)
rejected=false;
try
    action();
catch exception
    rejected=contains(exception.message,expected);
end
result=test_true(result,label,rejected,'opaque cores must not be materialised');
end


