% Compare function handle polyadic cores with explicit matrices.
% Syntax:
%
%                         result=test_fft_polyadic()
%
% Outputs:
%
%    result - regression checks for FFT actions, adjoints, and propagation
%
% ilya.kuprov@weizmann.ac.il

function result=test_fft_polyadic()

% Describe the independently materialised references
result=new_test_result('kernel/fft_polyadic','FFT polyadic cores',...
                       'Function handle cores must agree with explicit Fourier differentiation and exponentiation.');

% Exercise odd and even grids, including the zero Nyquist convention
spin_system.sys.enable={};
for npoints=[1 2 3 8 9]
    [~,explicit]=fourdif(spin_system,npoints,1);
    core=fft_core(npoints);
    block=reshape(sin(1:(3*npoints)),npoints,3)+...
          1i*reshape(cos(1:(3*npoints)),npoints,3);
    implicit=polyadic({{core,opium(2,1)}});
    reference=kron(explicit,eye(2));
    rhs=[block;block];
    result=test_close(result,['derivative ' num2str(npoints)],...
                      implicit*rhs,reference*rhs,1e-12,1e-12,...
                      'complex multiple right-hand sides match fourdif');
    result=test_close(result,['adjoint ' num2str(npoints)],...
                      implicit'*rhs,reference'*rhs,1e-12,1e-12,...
                      'the adjoint used in norm estimation is correct');
    result=test_close(result,['transpose ' num2str(npoints)],...
                      implicit.'*rhs,reference.'*rhs,1e-12,1e-12,...
                      'non-conjugating transpose has the correct sign');
    result=test_true(result,['size ' num2str(npoints)],...
                     isequal(size(implicit),[2*npoints 2*npoints]),...
                     'handle cores report their dimensions');
end

% A general complex rectangular handle tests dimensions and adjoints
matrix=[1+2*1i 2-1i 3;4 5*1i 6-2*1i];
core=struct('action',@(x)matrix*x,'adjoint',@(x)matrix'*x,'dims',size(matrix));
implicit=polyadic({{core,opium(2,1)}});
reference=kron(matrix,eye(2));
rhs=reshape(1:12,6,2);
result=test_close(result,'rectangular action',implicit*rhs,reference*rhs,...
                  1e-12,1e-12,'forward block dimensions are honoured');
result=test_close(result,'complex adjoint',(2*1i*implicit)'*reshape(1:8,4,2),...
                  (2*1i*reference)'*reshape(1:8,4,2),1e-12,1e-12,...
                  'scaling is absorbed by the matrix core and conjugated');
result=test_close(result,'complex transpose',implicit.'*reshape(1:8,4,2),...
                  reference.'*reshape(1:8,4,2),1e-12,1e-12,...
                  'transpose does not conjugate complex entries');
result=test_close(result,'double transpose',(implicit.').'*rhs,...
                  reference*rhs,1e-12,1e-12,...
                  'transposing twice restores the action');
result=test_close(result,'implicit composition',(implicit'*implicit)*rhs,...
                  reference'*reference*rhs,1e-12,1e-12,...
                  'composition buffers actions without multiplying cores');
result=test_close(result,'dense left action',ones(1,4)*implicit,...
                  ones(1,4)*reference,1e-12,1e-12,...
                  'dense left multiplication uses the adjoint route');
result=test_true(result,'handle structure',isa(simplify(polyadic({{core}})),'polyadic'),...
                 'a singleton handle core stays in the polyadic norm-estimation route');

% Arithmetic must preserve constructor metadata through core reordering
small=polyadic({{core}});
result=test_close(result,'numeric sum',(small+matrix)*ones(3,1),...
                  2*matrix*ones(3,1),1e-12,1e-12,'sum metadata stays aligned');
result=test_close(result,'implicit sum',(small+small)*ones(3,1),...
                  2*matrix*ones(3,1),1e-12,1e-12,'two implicit terms keep metadata');
result=test_close(result,'left Kronecker',kron(eye(2),small)*rhs,...
                  kron(eye(2),matrix)*rhs,1e-12,1e-12,'prepending a core keeps metadata');
result=test_close(result,'right Kronecker',kron(small,eye(2))*rhs,...
                  reference*rhs,1e-12,1e-12,'appending a core keeps metadata');
result=test_close(result,'zero scaling',(0*small)*ones(3,1),zeros(2,1),...
                  0,0,'zero terms and metadata are removed together');
result=test_true(result,'ordinary handle',isa(small.cores{1}{1},'function_handle'),...
                 'the stored core is an ordinary numerical action');
validate(small); allfinite(small); isreal(small); nnz(small);

% Affixes and nested flattening retain the actions and their dimensions
result=test_close(result,'scalar prefix',prefix(2*1i,small)*ones(3,1),...
                  2*1i*matrix*ones(3,1),1e-12,1e-12,'scalar prefix uses buffered arithmetic');
result=test_close(result,'scalar suffix',suffix(small,2*1i)*ones(3,1),...
                  2*1i*matrix*ones(3,1),1e-12,1e-12,'scalar suffix uses buffered arithmetic');
result=test_close(result,'nested flattening',simplify(polyadic({{eye(2),small}}))*rhs,...
                  kron(eye(2),matrix)*rhs,1e-12,1e-12,'flattened metadata tracks the cores');


% Scalar affixes must preserve dimensions, even after zero scaling
result=test_true(result,'scalar prefix size',isequal(size(prefix(2*1i,small)),[2 3]),...
                 'a scalar prefix must preserve both matrix dimensions');
result=test_true(result,'scalar suffix size',isequal(size(suffix(small,2*1i)),[2 3]),...
                 'a scalar suffix must preserve both matrix dimensions');
result=test_true(result,'zero prefix size',isequal(size(simplify(prefix(0,small))),[2 3]),...
                 'a zero scalar prefix yields a zero matrix of the original size');
result=test_close(result,'prefix after scaling',prefix([1 2],prefix(2*1i,small))*ones(3,1),...
                  [1 2]*(2*1i*matrix)*ones(3,1),1e-12,1e-12,...
                  'a subsequent matrix prefix sees the correct row dimension');

% Explicit inflation must materialise scalar boundary identities
numeric=polyadic({{3}});
left=inflate(prefix(2,numeric)); right=inflate(suffix(numeric,2));
result=test_true(result,'scalar prefix inflation',isa(left,'double')&&issparse(left)&&left==6,...
                 'a scalar prefix inflates to an explicit sparse matrix');
result=test_true(result,'scalar suffix inflation',isa(right,'double')&&issparse(right)&&right==6,...
                 'a scalar suffix inflates to an explicit sparse matrix');

% Dimensioned scalar affixes classify their numeric coefficients
real_poly=polyadic({{[1 2;3 4]}});
result=test_true(result,'real scalar prefix',isreal(prefix(2,real_poly)),...
                 'a real scalar prefix preserves real numeric data');
result=test_true(result,'real scalar suffix',isreal(suffix(real_poly,2)),...
                 'a real scalar suffix preserves real numeric data');
result=test_true(result,'complex scalar prefix',~isreal(prefix(2*1i,real_poly)),...
                 'a complex scalar prefix is not classified as real');
result=test_true(result,'complex scalar suffix',~isreal(suffix(real_poly,2*1i)),...
                 'a complex scalar suffix is not classified as real');

% Scalar implicit operators must compose as actions, not as coefficients
scalar_core=struct('action',@(x)2*1i*x,'adjoint',@(x)-2*1i*x,'dims',[1 1]);
scalar_poly=polyadic({{scalar_core}});
result=test_close(result,'scalar core composition',(scalar_poly*scalar_poly)*ones(1,2),...
                  -4*ones(1,2),1e-12,1e-12,'scalar implicit operands are buffered');
column=[1;2*1i];
column_core=struct('action',@(x)column*x,'adjoint',@(x)column'*x,'dims',[2 1]);
result=test_close(result,'column scalar composition',...
                  (polyadic({{column_core}})*scalar_poly)*ones(1,2),...
                  2*1i*column*ones(1,2),1e-12,1e-12,...
                  'rectangular implicit operators compose with scalar implicit operators');

% The scalar numerical probe used by norm estimation must not scale an object
result=test_close(result,'singleton norm',cheap_norm(scalar_poly),2,1e-12,1e-12,...
                  'norm estimation obtains a numeric action for a scalar probe');
result=test_close(result,'singleton direct action',scalar_poly*1,2*1i,1e-12,1e-12,...
                  'mtimes applies a scalar-sized numeric state through the existing product path');

% Sparse scalar states use the same numerical action as dense scalar states
result=test_close(result,'sparse singleton action',scalar_poly*sparse(1),2*1i,...
                  1e-12,1e-12,'a sparse scalar state evaluates the implicit action');
result=test_close(result,'sparse column action',polyadic({{column_core}})*sparse(2),2*column,...
                  1e-12,1e-12,'a sparse one-element state evaluates a column operator');

% Rectangular norm probes must also be evaluated as numeric actions
result=test_close(result,'column implicit norm',cheap_norm(polyadic({{column_core}})),...
                  norm(column,1),1e-12,1e-12,...
                  'a scalar probe of a column operator is a numerical action');
row=[1+2*1i 3-4*1i];
row_core=struct('action',@(x)row*x,'adjoint',@(x)row'*x,'dims',[1 2]);
row_est=cheap_norm(polyadic({{row_core}}));
result=test_close(result,'row implicit norm',row_est,cheap_norm(polyadic({{row}})),...
                  1e-12,1e-12,'implicit and numeric row operators give the same estimate');
result=test_true(result,'row norm lower bound',isfinite(row_est)&&...
                 (row_est>0)&&(row_est<=norm(row,1)*(1+1e-12)),...
                 'the estimate is finite and respects the lower-bound contract');

% Diagnostic output must use the represented dimensions, not handle sizes
diagram=evalc('polinfo(small,0,''implicit'');');
result=test_true(result,'implicit diagram',contains(diagram,'handle 1 [2x3]'),...
                 'polinfo labels the action with its stored dimensions');

% Single-precision actions preserve the state precision
single_rhs=single(rhs);
observed=implicit*single_rhs;
result=test_true(result,'single precision',isa(observed,'single'),...
                 'implicit action accumulation follows the input block precision');
result=test_close(result,'single precision action',double(observed),...
                  double(reference*single_rhs),1e-5,1e-5,...
                  'single-precision action agrees with the explicit matrix');

% Direct tensor actions reject malformed construction metadata
result=check_rejection(result,'core dimensions rejection',...
                       @()kronm({struct('action',@(x)x,'dims',2)},ones(2,1)),...
                       'dims must be a row of two positive integers');
result=check_rejection(result,'missing action rejection',...
                       @()kronm({struct('dims',[2 2])},ones(2,1)),...
                       'implicit factors need a function handle action');
result=check_rejection(result,'action type rejection',...
                       @()kronm({struct('dims',[2 2],'action','bad')},ones(2,1)),...
                       'implicit factors need a function handle action');

% Explicit materialisation must not open function handle cores
result=check_rejection(result,'full rejection',@()full(implicit),...
                       'function handle cores cannot be materialised');
result=check_rejection(result,'inflate rejection',@()inflate(implicit),...
                       'function handle cores cannot be materialised');
result=test_close(result,'singleton scaling',(polyadic({{core}})*2*1i)'*ones(2,1),...
                  (matrix*2*1i)'*ones(2,1),1e-12,1e-12,...
                  'singleton implicit cores support scalar multiplication');

% Build a small Hermitian rotor generator with a noncommuting spin term
[~,explicit]=fourdif(spin_system,9,1); core=fft_core(9);
spin_term=[1 0.3;0.3 -1];
reference=kron(diag(cos(2*pi*(0:8)/9)),spin_term)+...
          1i*kron(explicit,eye(2));
implicit=polyadic({{diag(cos(2*pi*(0:8)/9)),spin_term}})+...
         1i*polyadic({{core,opium(2,1)}});
spin_system.sys.enable={}; spin_system.sys.disable={};
spin_system.bas.formalism='zeeman-liouv'; spin_system.sys.output='hush';
spin_system.tols.prop_chop=1e-12;
spin_system.tols.dense_matrix=0.5; spin_system.tols.small_matrix=200;
rhs=reshape(sin(1:36),18,2)+1i*reshape(cos(1:36),18,2);
result=test_close(result,'Taylor propagation',...
                  step(spin_system,implicit,rhs,0.1),expm(-1i*reference*0.1)*rhs,...
                  1e-11,1e-11,'the existing step algorithm handles function handle cores');
result=test_close(result,'singleton propagation',step(spin_system,scalar_poly,1,0.1),...
                  exp(0.2),1e-12,1e-12,'a scalar implicit generator propagates a scalar state');
result=test_close(result,'cleanup preserves action',...
                  clean_up(spin_system,implicit,eps)*rhs,reference*rhs,...
                  1e-12,1e-12,'cleanup does not touch opaque actions');
result=check_rejection(result,'standalone cleanup handle rejection',...
                       @()clean_up(spin_system,@sin,-1),'A must be numeric');

end

% FFT actions with the first derivative Nyquist convention of fourdif
function core=fft_core(npoints)
kern=fftdiff(1,npoints,2*pi/npoints).';
if mod(npoints,2)==0, kern(npoints/2+1)=0; end
core=struct('action',@(x)ifft(kern.*fft(x,[],1),[],1),...
            'adjoint',@(x)ifft(conj(kern).*fft(x,[],1),[],1),...
            'dims',[npoints npoints]);
end

% Check that an invalid operation fails with the expected message
function result=check_rejection(result,label,action,expected)
rejected=false;
try
    action();
catch exception
    rejected=contains(exception.message,expected);
end
result=test_true(result,label,rejected,'the operation must reject the invalid input or request');
end


