% Tests Liouville-space commutation superoperators. Syntax:
%
%                    result=test_liouville_commutator()
%
% Outputs:
%
%     result  - regression test result with explanatory messages
%
% The test checks that the commutation superoperator generated by operator()
% is equal to the difference between left and right product superoperators.
%
% ilya.kuprov@weizmann.ac.il

function result=test_liouville_commutator()

% Announce the test target
fprintf('TESTING: Liouville commutation superoperator\n');

% State the Liouville-space target of the test
result=new_test_result('kernel/liouville_commutator',...
                       'Liouville commutation superoperator',...
                       'commutation superoperators must be left multiplication minus right multiplication.');

% Build a one-proton Zeeman Liouville-space spin system
sys.magnet=0;
sys.isotopes={'1H'};
inter.zeeman.scalar={0};
bas.formalism='zeeman-liouv';
bas.approximation='none';
spin_system=test_spin_system(sys,inter,bas);

% Generate three forms of the same labelled operator
L_comm=operator(spin_system,'Lz',1,'comm');
L_left=operator(spin_system,'Lz',1,'left');
L_right=operator(spin_system,'Lz',1,'right');

% Check the superoperator identity
result=test_close(result,'comm=left-right',L_comm,L_left-L_right,1e-15,1e-15,...
                  'the Liouville commutator is A*rho-rho*A');

end

