% Tests grid and spherical geometry helpers. Syntax:
%
%                    result=test_grid_geometry_suite()
%
% Outputs:
%
%     result  - regression test result with explanatory messages
%
% The test checks spherical arc and area formulae, Gauss-Legendre exactness,
% polar-grid structure, spherical quadrature weights, Voronoi solid angles,
% grid products, SHREWD weights, and seeded repulsion-grid invariants.
%
% ilya.kuprov@weizmann.ac.il

function result=test_grid_geometry_suite()

% State the grid target of the test
result=new_test_result('kernel/grid_geometry_suite',...
                       'Grid and spherical geometry helpers',...
                       'grid helpers must return unit vectors, positive normalised weights, and exact low-order geometry.');

% Define Cartesian basis vectors on the unit sphere
ex=[1;0;0];
ey=[0;1;0];
ez=[0;0;1];

% Check spherical arc lengths between orthogonal and opposite points
result=test_close(result,'arclength orthogonal axes',arclength(ex,ey),pi/2,1e-15,1e-15,...
                  'orthogonal unit vectors subtend a quarter great circle');
result=test_close(result,'arclength antipodal axes',arclength(ex,-ex),pi,1e-15,1e-15,...
                  'antipodal unit vectors subtend half of a great circle');

% Check the area of the positive-octant spherical triangle
result=test_close(result,'sphtarea octant unsigned',sphtarea(ex,ey,ez,'unsigned'),pi/2,1e-15,1e-15,...
                  'the triangle bounded by three coordinate great circles occupies one eighth of the sphere');
result=test_close(result,'sphtarea octant signed orientation',sphtarea(ex,ez,ey,'signed'),-pi/2,1e-15,1e-15,...
                  'reversing vertex orientation changes the sign of the signed spherical area');

% Check spherical midpoint subdivision
[rxy,ryz,rzx]=sphtrsubd(ex,ey,ez);
result=test_close(result,'sphtrsubd xy midpoint',rxy,(ex+ey)/sqrt(2),1e-15,1e-15,...
                  'the midpoint of a quadrant arc lies along the normalised chord sum');
result=test_close(result,'sphtrsubd unit norms',[norm(rxy,2);norm(ryz,2);norm(rzx,2)],ones(3,1),1e-15,1e-15,...
                  'subdivision points must stay on the unit sphere');

% Check Gauss-Legendre quadrature on low-degree polynomials
[xg,wg]=gaussleg(-1,1,4);
result=test_true(result,'gaussleg positive weights',all(wg>0),...
                 'Gauss-Legendre quadrature weights on a finite interval are positive');
result=test_true(result,'gaussleg sorted nodes',all(diff(xg)>0),...
                 'the returned nodes are sorted in ascending order');
result=test_close(result,'gaussleg constant integral',sum(wg),2,1e-14,1e-14,...
                  'the integral of one over [-1,1] is two');
result=test_close(result,'gaussleg odd integral',sum(wg.*xg),0,1e-14,1e-14,...
                  'odd functions integrate to zero on a symmetric interval');
result=test_close(result,'gaussleg quadratic integral',sum(wg.*xg.^2),2/3,1e-14,1e-14,...
                  'the integral of x^2 over [-1,1] is two thirds');

% Check polar grid point count, radial bounds, and Laplacian nullspace
[~,r_pol,L_pol]=grid_polar(4,2);
npnts=3*(4-1)^2+2*(4-1)+1;
result=test_close(result,'grid_polar point count',numel(r_pol),npnts,0,0,...
                  'the balanced polar grid has 3*(n-1)^2+2*(n-1)+1 points');
result=test_close(result,'grid_polar origin radius',r_pol(1),0,1e-15,1e-15,...
                  'the first polar grid point is the origin');
result=test_true(result,'grid_polar radial bounds',all(r_pol>=0)&&max(r_pol)<=2,...
                 'all polar grid radii must lie between zero and rmax');
result=test_close(result,'grid_polar Laplacian size',size(L_pol),[npnts npnts],0,0,...
                  'the polar-grid Laplacian acts on one scalar per grid point');
result=test_close(result,'grid_polar constant nullspace',L_pol*ones(npnts,1),zeros(npnts,1),1e-12,1e-12,...
                  'the discrete Laplacian of a constant function should vanish');

% Check Fibonacci grid unit vectors and normalised Voronoi weights
[alps,bets,gams,whts]=grid_fibon('fib',3);
xyz=[sin(bets).*cos(gams) sin(bets).*sin(gams) cos(bets)];
result=test_close(result,'grid_fibon point count',numel(whts),7,0,0,...
                  'the fib parameter n produces 2*n+1 spherical points');
result=test_close(result,'grid_fibon zero alphas',alps,zeros(size(alps)),1e-15,1e-15,...
                  'Fibonacci grids are two-angle grids with zero alpha angles');
result=test_close(result,'grid_fibon unit vectors',sqrt(sum(xyz.^2,2)),ones(numel(whts),1),1e-14,1e-14,...
                  'spherical angles generated by the grid must lie on the unit sphere');
result=test_true(result,'grid_fibon positive weights',all(whts>0),...
                 'Voronoi cell weights for a non-degenerate spherical grid are positive');
result=test_close(result,'grid_fibon normalised weights',sum(whts),1,1e-12,1e-12,...
                  'Spinach stores two-angle spherical quadrature weights normalised to one');

% Check igloo grid weights on a small deterministic grid
[alps,bets,gams,whts]=grid_igloo(4);
xyz=[sin(bets).*cos(gams) sin(bets).*sin(gams) cos(bets)];
result=test_close(result,'grid_igloo zero alphas',alps,zeros(size(alps)),1e-15,1e-15,...
                  'Igloo grids are two-angle grids with zero alpha angles');
result=test_close(result,'grid_igloo unit vectors',sqrt(sum(xyz.^2,2)),ones(numel(whts),1),1e-14,1e-14,...
                  'igloo grid angles must describe unit vectors');
result=test_true(result,'grid_igloo positive weights',all(whts>0),...
                 'Voronoi weights of the igloo grid must be positive');
result=test_close(result,'grid_igloo normalised weights',sum(whts),1,1e-12,1e-12,...
                  'normalised two-angle spherical grid weights must sum to one');

% Check a triangular grid without invoking the expensive Voronoi weights
[alps,bets,gams]=grid_trian('asg',2);
xyz=[sin(bets).*cos(gams) sin(bets).*sin(gams) cos(bets)];
result=test_close(result,'grid_trian zero alphas',alps,zeros(size(alps)),1e-15,1e-15,...
                  'triangular grids are two-angle grids with zero alpha angles');
result=test_close(result,'grid_trian unit vectors',sqrt(sum(xyz.^2,2)),ones(numel(bets),1),1e-14,1e-14,...
                  'triangular grid angles must describe unit vectors');

% Check convex hull facets and directed edge list on a tetrahedron
xyz_tet=[1 1 -1 -1;1 -1 1 -1;1 -1 -1 1];
xyz_tet=xyz_tet./sqrt(sum(xyz_tet.^2,1));
theta=acos(xyz_tet(3,:)).';
phi=atan2(xyz_tet(2,:),xyz_tet(1,:)).';
[hull,edges]=get_hull(theta,phi);
result=test_close(result,'get_hull tetrahedron facets',size(hull,1),4,0,0,...
                  'a tetrahedron has four triangular hull facets');
result=test_close(result,'get_hull directed edges',size(edges,1),12,0,0,...
                  'six undirected tetrahedron edges appear in both directions for plotting');

% Check Voronoi solid angles on a regular tetrahedron
[vertices,indices,~,sangles]=voronoisphere(xyz_tet,pi/3);
result=test_true(result,'voronoisphere positive cells',all(sangles>0),...
                 'regular tetrahedron Voronoi cells must have positive solid angle');
result=test_close(result,'voronoisphere total solid angle',sum(sangles),4*pi,1e-12,1e-12,...
                  'Voronoi cells tile the whole unit sphere');
result=test_close(result,'voronoisphere equal tetrahedron cells',sangles,pi*ones(4,1),1e-12,1e-12,...
                  'symmetry gives four equal cells of area pi steradians');
S_cell=one_vcell_solidangle(vertices(:,indices{1}),xyz_tet(:,1));
result=test_close(result,'one_vcell_solidangle guided cell',S_cell,sangles(1),1e-12,1e-12,...
                  'guided single-cell solid angle must match the Voronoi tessellation result');
result=test_close(result,'vcell_solidangle guided cells',vcell_solidangle(vertices,indices,xyz_tet),sangles,1e-12,1e-12,...
                  'guided multi-cell solid angles must match the Voronoi tessellation result');

% Check direct-product grid weights and cardinality
angles1=[0 0 0;pi/2 0 0];
angles2=[0 0 0;0 pi/2 0];
weights1=[0.25;0.75];
weights2=[0.4;0.6];
[angles,weights]=grid_kron(angles1,weights1,angles2,weights2);
result=test_close(result,'grid_kron point count',size(angles,1),4,0,0,...
                  'the direct-product grid cardinality is the product of input cardinalities');
result=test_close(result,'grid_kron weights',weights,kron(weights1,weights2),1e-15,1e-15,...
                  'direct-product quadrature weights are Kronecker products of input weights');

% Check SHREWD and grid-test invariants at rank zero and one
weights=shrewd(zeros(4,1),theta,phi,1,1e-8);
result=test_true(result,'shrewd positive weights',all(weights>0),...
                 'SHREWD weights should remain positive for a symmetric rank-one tetrahedral grid');
result=test_close(result,'shrewd normalisation',sum(weights),1,1e-12,1e-12,...
                  'SHREWD weights are normalised after solving the spherical-function system');
profile=grid_test(0,0,0,1,0,'D_lmn');
result=test_close(result,'grid_test rank zero residual',profile,0,1e-15,1e-15,...
                  'a single unit-weight point integrates the constant Wigner function exactly');

% Check spatial-grid point estimate against the documented formula
amps=[0.01 -0.02];
durs=[1e-3 2e-3];
coh_order=2;
sample_size=0.01;
n_ref=ceil(abs(coh_order*spin('1H')*sum(abs(amps.*durs)))*sample_size/pi);
result=test_close(result,'ngridpts formula',ngridpts(amps,durs,'1H',coh_order,sample_size),n_ref,0,0,...
                  'the grid point estimate is the Nyquist count for the worst-case gradient spiral');

% Check seeded repulsion grid invariants without relying on a particular random cloud
rng_state=rng;
rng(1,'twister');
[~,bets,gams,whts]=repulsion(5,3,1);
rng(rng_state);
xyz=[sin(bets).*cos(gams) sin(bets).*sin(gams) cos(bets)];
result=test_close(result,'repulsion uniform weights',whts,ones(5,1)/5,1e-15,1e-15,...
                  'repulsion currently assigns uniform quadrature weights');
result=test_close(result,'repulsion unit vectors',sqrt(sum(xyz.^2,2)),ones(5,1),1e-14,1e-14,...
                  'repulsion grid angles must describe points on a unit sphere');

end


