% Tests the spin-bearing acetonitrile in the shared Diels-Alder model.
% Syntax:
%
%                       result=test_dac_solvent()
%
% Outputs:
%
%    result - molecular-input, solvent relaxation, and preparation checks
%
% The full molecular input retains thirty protons. Numerical relaxation
% uses a one-spin-order truncation of each molecule, not a full spectrum.
%
% ilya.kuprov@weizmann.ac.il

function result=test_dac_solvent()

% Load the shared physical definition
fprintf('TESTING: Diels-Alder solvent spin preservation\n');
result=new_test_result('kernel/dac_solvent','Diels-Alder solvent',...
                      'Acetonitrile retains its three protons and relaxation.');
[sys,inter,bas,kin]=dac_reaction();
result=test_true(result,'thirty protons',numel(sys.isotopes)==30&&...
                 all(strcmp(sys.isotopes,'1H'))&&...
                 isequal(sys.labels(28:30),{'H28','H29','H30'}),...
                 'the shared molecule keeps the original solvent labels and isotopes');
result=test_true(result,'five spin-bearing parts',...
                 isequal(inter.chem.parts,{1:6,7:9,10:18,19:27,28:30}),...
                 'the fifth substance contains the three solvent protons');
result=test_true(result,'unit reference concentrations',...
                 isequal(inter.chem.concs,ones(1,5)),...
                 'the molecular input does not suppress solvent concentration');
result=test_true(result,'solvent shifts and coordinates',...
                 all(cellfun(@(x)isequal(x,2*eye(3)),inter.zeeman.matrix(28:30)))&&...
                 all(cellfun(@isempty,inter.coordinates(28:30))),...
                 'solvent protons have isotropic 2 ppm shifts and no coordinates');
result=test_true(result,'solvent coupling',...
                 all(cellfun(@(x)isempty(x)||all(x==0,'all'),inter.coupling.scalar(28:30,:)),'all'),...
                 'the solvent has no scalar couplings');
result=test_true(result,'relaxation inputs',...
                 isequal(inter.relaxation,{'redfield','t1_t2'})&&...
                 isequal(cell2mat(inter.r1_rates),[zeros(27,1);0.5*ones(3,1)])&&...
                 isequal(inter.r1_rates,inter.r2_rates),...
                 'the original solvent R1 and R2 are 0.5 per second');
result=test_true(result,'reaction records omit solvent',...
                 isequal(kin,inter.chem.reactions)&&...
                 all(cellfun(@(x)~ismember(5,[x.reactants x.products]),kin)),...
                 'restoring solvent does not add a chemical reaction');

% Exercise combined relaxation with compact one-spin-order molecular bases
sys.magnet=14.1; bas=rmfield(bas,{'connectivity','prox_level'});
bas.approximation={'IK-0','IK-0','IK-0','IK-0','IK-0'};
bas.inter_level={1,1,1,1,1};
s=assume(test_spin_system(sys,inter,bas),'nmr'); R=relaxation(s);
for axis={'Lz','L+'}
    rho=coil_state(s,axis{1},28:30,'exact');
    result=test_close(result,['solvent ' axis{1} ' decay'],R*rho,-0.5*rho,...
                      1e-12,0,'the solvent mode retains its specified relaxation rate');
end

% Keep the nonzero-concentration solvent unexcited in reacting NMR preparation
rho=state(s,'Lz',[s.chem.parts{1:4}]);
solvent=(s.bas.offsets(5)+1):s.bas.offsets(6);
result=test_true(result,'unexcited solvent',nnz(rho(solvent))==0,...
                 'selecting reacting species excludes solvent magnetisation');

end


