% Tests permutation group database metadata. Syntax:
%
%                    result=test_perm_group_suite()
%
% Outputs:
%
%     result  - regression test result with explanatory messages
%
% The test checks the real-valued-character Abelian permutation subgroups
% against explicit element tables, explicit character tables, character
% orthogonality, closure, commutativity, and involution order.
%
% ilya.kuprov@weizmann.ac.il

function result=test_perm_group_suite()

% Announce the test target
fprintf('TESTING: Permutation group metadata\n');

% State the utility target of the test
result=new_test_result('kernel/perm_group_suite',...
                       'Permutation group metadata',...
                       'real-valued-character Abelian permutation subgroup tables must be exact and internally consistent.');

% Check the S6 Abelian subgroup table
G=perm_group('S6A');
elements_ref=[1 2 3 4 5 6;2 1 4 3 5 6;3 4 1 2 5 6;4 3 2 1 5 6;...
              1 2 3 4 6 5;2 1 4 3 6 5;3 4 1 2 6 5;4 3 2 1 6 5];
chars_ref=[1 1 1 1 1 1 1 1;...
           1 1 -1 -1 1 1 -1 -1;...
           1 -1 1 -1 1 -1 1 -1;...
           1 -1 -1 1 1 -1 -1 1;...
           1 1 1 1 -1 -1 -1 -1;...
           1 1 -1 -1 -1 -1 1 1;...
           1 -1 1 -1 -1 1 -1 1;...
           1 -1 -1 1 -1 1 1 -1];
result=test_close(result,'perm_group S6A elements',G.elements,elements_ref,1e-15,1e-15,...
                  'S6A is represented by the direct product of S4A and S2');
result=test_close(result,'perm_group S6A characters',G.class_characters,chars_ref,1e-15,1e-15,...
                  'S6A has the real character table of C2 x C2 x C2');

% Check the S8 Abelian subgroup table
G=perm_group('S8A');
elements_ref=[1 2 3 4 5 6 7 8;2 1 4 3 5 6 7 8;3 4 1 2 5 6 7 8;4 3 2 1 5 6 7 8;...
              1 2 3 4 6 5 8 7;2 1 4 3 6 5 8 7;3 4 1 2 6 5 8 7;4 3 2 1 6 5 8 7;...
              1 2 3 4 7 8 5 6;2 1 4 3 7 8 5 6;3 4 1 2 7 8 5 6;4 3 2 1 7 8 5 6;...
              1 2 3 4 8 7 6 5;2 1 4 3 8 7 6 5;3 4 1 2 8 7 6 5;4 3 2 1 8 7 6 5];
chars_ref=[1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1;...
           1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1;...
           1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1;...
           1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1;...
           1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1;...
           1  1 -1 -1  1  1 -1 -1 -1 -1  1  1 -1 -1  1  1;...
           1 -1  1 -1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1;...
           1 -1 -1  1  1 -1 -1  1 -1  1  1 -1 -1  1  1 -1;...
           1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1;...
           1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1;...
           1 -1  1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1;...
           1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1  1 -1;...
           1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1;...
           1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1;...
           1 -1  1 -1 -1  1 -1  1 -1  1 -1  1  1 -1  1 -1;...
           1 -1 -1  1 -1  1  1 -1 -1  1  1 -1  1 -1 -1  1];
result=test_close(result,'perm_group S8A elements',G.elements,elements_ref,1e-15,1e-15,...
                  'S8A is represented by a maximal C2 x C2 x C2 x C2 subgroup');
result=test_close(result,'perm_group S8A characters',G.class_characters,chars_ref,1e-15,1e-15,...
                  'S8A has the real character table of C2 x C2 x C2 x C2');

% Check structural consistency of all real-valued-character Abelian options
group_names={'S4A','S6A','S8A'};
group_degrees=[4 6 8];
group_orders=[4 8 16];
for n=1:numel(group_names)

    % Get the group under test
    G=perm_group(group_names{n});

    % Check scalar group metadata
    result=test_true(result,[group_names{n} ' scalar metadata'],...
                     (G.order==group_orders(n))&&(G.nclasses==group_orders(n))&&(G.n_irreps==group_orders(n)),...
                     'Abelian real-character subgroup metadata must match the group order');
    result=test_true(result,[group_names{n} ' maximum real-character order'],...
                     G.order==2^floor(group_degrees(n)/2),...
                     'real-character Abelian subgroup order must be maximal for the permutation degree');

    % Check class and irrep dimensions
    result=test_close(result,[group_names{n} ' singleton classes'],G.class_sizes,ones(1,group_orders(n)),1e-15,1e-15,...
                      'Abelian subgroup conjugacy classes are singletons');
    result=test_close(result,[group_names{n} ' irrep dimensions'],G.irrep_dims,ones(1,group_orders(n)),1e-15,1e-15,...
                      'Abelian subgroup irreducible representations are one-dimensional');

    % Check character reality and orthogonality
    result=test_true(result,[group_names{n} ' real characters'],...
                     isreal(G.class_characters)&&all(abs(G.class_characters(:))==1),...
                     'real-valued-character Abelian subgroup characters must be signs');
    result=test_close(result,[group_names{n} ' character orthogonality'],...
                      G.class_characters*G.class_characters.',group_orders(n)*eye(group_orders(n)),1e-15,1e-15,...
                      'Abelian subgroup character rows must be orthogonal');

    % Initialise multiplication checks
    group_closed=true; group_comm=true; group_invol=true; group_perm=true;
    identity=1:group_degrees(n);

    % Check every permutation and every product
    for k=1:G.order
        element=G.elements(k,:);
        group_perm=group_perm&&isequal(sort(element),identity);
        group_invol=group_invol&&isequal(element(element),identity);
        for m=1:G.order
            prod_left=G.elements(k,G.elements(m,:));
            prod_right=G.elements(m,G.elements(k,:));
            group_closed=group_closed&&ismember(prod_left,G.elements,'rows');
            group_comm=group_comm&&isequal(prod_left,prod_right);
        end
    end

    % Check permutation-table structure
    result=test_true(result,[group_names{n} ' permutation rows'],group_perm,...
                     'all group elements must be valid permutation rows');
    result=test_true(result,[group_names{n} ' closure'],group_closed,...
                     'the listed permutation rows must be closed under composition');
    result=test_true(result,[group_names{n} ' commutativity'],group_comm,...
                     'the listed permutation rows must commute');
    result=test_true(result,[group_names{n} ' involutions'],group_invol,...
                     'all real-character Abelian subgroup elements must square to identity');

    % Check maximality inside the ambient symmetric group
    central_count=0; all_perms=perms(identity);
    for k=1:size(all_perms,1)
        central_perm=true;
        for m=1:G.order
            central_perm=central_perm&&isequal(all_perms(k,G.elements(m,:)),G.elements(m,all_perms(k,:)));
        end
        central_count=central_count+central_perm;
    end
    result=test_true(result,[group_names{n} ' centraliser'],central_count==G.order,...
                     'the subgroup centraliser must be the subgroup itself');

end


end
