% Tests hard pi-pulse rotation. Syntax:
%
%                    result=test_pi_pulse_rotation()
%
% Outputs:
%
%     result  - regression test result with explanatory messages
%
% The test applies a hard pi rotation about X to longitudinal magnetisation;
% the physically correct answer is inversion, Lz -> -Lz.
%
% ilya.kuprov@weizmann.ac.il

function result=test_pi_pulse_rotation()

% Announce the test target
fprintf('TESTING: Hard pi pulse rotation\n');

% State the pulse target of the test
result=new_test_result('kernel/pi_pulse_rotation',...
                       'Hard pi pulse rotation',...
                       'a pi rotation around X must invert longitudinal magnetisation.');

% Build a one-proton Hilbert-space spin system
sys.magnet=0;
sys.isotopes={'1H'};
inter.zeeman.scalar={0};
bas.formalism='zeeman-hilb';
bas.approximation='none';
spin_system=test_spin_system(sys,inter,bas);

% Apply the rotation generated by Lx
Lx=operator(spin_system,'Lx',1);
Lz=state(spin_system,'Lz',1);
rho_obs=step(spin_system,Lx,Lz,pi);

% Check the physical rotation result
result=test_close(result,'Lz inverted by X pi pulse',rho_obs,-Lz,1e-14,1e-14,...
                  'active rotation by pi around X maps the z axis to -z');

end

